# Project info
sonar.organization=vws
sonar.projectKey=minvws_nl-mgo-package-healthchecker
sonar.projectName=nl-mgo-package-healthchecker

# Info links shown in SonarCloud
sonar.links.homepage=https://github.com/minvws/nl-mgo-package-healthchecker

# Encoding and language specific properties
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11

# Analysis scoping
sonar.sources=src
sonar.tests=tests

# Code coverage
sonar.python.coverage.reportPaths=coverage.xml
